version: '3'
services:
  back-end:
    image: rubiksel/docker_tp:latest
    ports: 
      - "5000:5000"
    environment: 
      - CURRENT_ENVIRONMENT=development
    volumes:
      - ./logs:/app/back/logs

  front-end:
    image: rubiksel/front_end:latest
    ports:
      - "80:80"
    environment:
      - WS_BACK_URL=http://back-end:5000